In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True).astype(int)

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
independent=dataset[['age', 'bmi', 'children','sex_male','smoker_yes']]

In [6]:
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [7]:
dependent=dataset[['charges']]

In [8]:
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [9]:
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [12]:
X_train

array([[-1.5330973 , -0.36100765, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.278355  , -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.51612426,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.84052963, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.75787698, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.95941426, -0.06746417, -0.97676557, -0.50466988]])

In [13]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['squared_error','friedman_mse','absolute_error','poisson'],'max_features': ['auto','sqrt','log2'],'splitter':['best','random']}

grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1)
# fitting the model for grid search
grid.fit(X_train, Y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning:
40 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.66422265 0.55165376 0.63927872 0.60874674
        nan        nan 0.68126098 0.58761108 0.6046314  0.5979597
        nan        nan 0.62780914 0.58786053 0.60447921 0.6620562
        nan        nan 0.63419336 0.59516221 0.62162315 0.6026507 ]
  warnings.warn(

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [14]:
result=grid.cv_results_

grid_predictions=grid.predict(X_test)

from sklearn.metrics import r2_score
r_score=r2_score(Y_test,grid_predictions)

print("R_Score Value for BEST parameter {}".format(grid.best_params_),r_score)

R_Score Value for BEST parameter {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'splitter': 'best'} 0.6468958132248529

In [15]:
table=pd.DataFrame.from_dict(result)

In [16]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002509,0.000169,0.000000,0.000000,squared_error,auto,best,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
1,0.002316,0.000123,0.000000,0.000000,squared_error,auto,random,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
2,0.009552,0.001259,0.004977,0.000554,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.748543,0.444582,0.688171,0.318267,0.585600,0.557033,0.157698,16
3,0.007253,0.000794,0.005107,0.001406,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.789323,0.508273,0.646960,0.571075,0.643965,0.631919,0.093955,5
4,0.008091,0.000549,0.005019,0.000269,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.714737,0.706063,0.597339,0.621059,0.670256,0.661891,0.046148,2
5,0.008600,0.001309,0.005945,0.001460,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.706733,0.568992,0.654513,0.515140,0.640213,0.617118,0.067347,7
6,0.001940,0.000550,0.000000,0.000000,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
7,0.001751,0.000091,0.000000,0.000000,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
8,0.008559,0.001051,0.005299,0.000294,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.490511,0.643815,0.520505,0.594272,0.668328,0.583486,0.068651,12
9,0.007799,0.000857,0.005225,0.000560,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.762779,0.503896,0.520645,0.619317,0.479006,0.577129,0.104333,13
10,0.008520,0.000540,0.005434,0.000951,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.759831,0.542821,0.619556,0.564719,0.631333,0.623652,0.075667,6
11,0.008242,0.000766,0.004291,0.000400,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.642001,0.595939,0.626516,0.425208,0.584675,0.574868,0.077605,14
12,0.001628,0.000152,0.000000,0.000000,absolute_error,auto,best,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
13,0.001553,0.000076,0.000000,0.000000,absolute_error,auto,random,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
14,0.025181,0.004253,0.005016,0.000783,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.729281,0.600049,0.677159,0.560298,0.604414,0.634240,0.060665,4
15,0.020758,0.001916,0.005246,0.000693,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.669269,0.549261,0.646474,0.592308,0.539029,0.599268,0.051588,8
16,0.026064,0.004039,0.005381,0.000358,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.744346,0.504235,0.554904,0.641429,0.474604,0.583904,0.098169,11
17,0.020737,0.002153,0.004587,0.000776,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.701292,0.586823,0.584628,0.329921,0.609183,0.562369,0.123787,15
18,0.001726,0.000273,0.000000,0.000000,poisson,auto,best,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
19,0.001602,0.000152,0.000000,0.000000,poisson,auto,random,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
20,0.007837,0.000876,0.004568,0.000376,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.716726,0.644854,0.561100,0.708099,0.672219,0.660599,0.056017,3
21,0.007390,0.000646,0.004054,0.000556,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.604229,0.661974,0.566991,0.612510,0.544718,0.598084,0.040355,9
22,0.007988,0.000421,0.004454,0.000382,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.705613,0.604974,0.686823,0.710228,0.675938,0.676715,0.037968,1
23,0.007063,0.000851,0.003815,0.000265,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.508257,0.567761,0.651572,0.601748,0.594060,0.584679,0.046863,10

In [16]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 35
BMI: 36
Children: 2
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 1

In [17]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
#␣,change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[48549.]