In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True).astype(int)

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
independent=dataset[['age', 'bmi', 'children','sex_male','smoker_yes']]

In [6]:
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [7]:
dependent=dataset[['charges']]

In [8]:
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [9]:
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [12]:
X_train

array([[-1.5330973 , -0.36100765, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.278355  , -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.51612426,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.84052963, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.75787698, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.95941426, -0.06746417, -0.97676557, -0.50466988]])

In [13]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['squared_error', 'absolute_error', 'friedman_mse', 'poisson'],'max_features': ['auto','sqrt','log2'],'n_estimators':[10,100]}

grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose= 3,n_jobs=-1)
# fitting the model for grid search
grid.fit(X_train, Y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning:
40 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
36 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
4 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.78431246 0.80720251 0.79435266 0.8089034
        nan        nan 0.78295683 0.81193234 0.79970345 0.81478634
        nan        nan 0.78757533 0.80611008 0.78590915 0.8103666
        nan        nan 0.78740958 0.81182521 0.79765164 0.80837434]
  warnings.warn(
C:\Anaconda3\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse', 'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [14]:
result=grid.cv_results_

grid_predictions=grid.predict(X_test)

from sklearn.metrics import r2_score
r_score=r2_score(Y_test,grid_predictions)

print("R_Score Value for BEST parameter {}".format(grid.best_params_),r_score)

R_Score Value for BEST parameter {'criterion': 'absolute_error', 'max_features': 'log2', 'n_estimators': 100} 0.8725612043307683

In [15]:
table=pd.DataFrame.from_dict(result)

In [16]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003145,0.000564,0.000000,0.000000,squared_error,auto,10,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
1,0.002805,0.000478,0.000000,0.000000,squared_error,auto,100,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
2,0.078252,0.008469,0.010765,0.001082,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.852863,0.755506,0.753490,0.814249,0.745454,0.784312,0.042155,15
3,0.595935,0.013864,0.043098,0.005437,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.864536,0.792651,0.794497,0.817240,0.767088,0.807203,0.032773,7
4,0.073532,0.003225,0.010633,0.001351,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.848148,0.769299,0.779873,0.817740,0.756703,0.794353,0.033751,11
5,0.606011,0.030561,0.040697,0.003674,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.861161,0.790968,0.799430,0.822476,0.770483,0.808903,0.030992,5
6,0.002098,0.000316,0.000000,0.000000,absolute_error,auto,10,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
7,0.002775,0.000516,0.000000,0.000000,absolute_error,auto,100,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
8,0.163440,0.012422,0.010603,0.001586,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.847871,0.765003,0.761793,0.794242,0.745875,0.782957,0.036018,16
9,1.497253,0.049368,0.041897,0.008428,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.865347,0.799650,0.800213,0.819607,0.774845,0.811932,0.030251,2
10,0.166762,0.004398,0.010308,0.002619,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.852710,0.793279,0.780402,0.798811,0.773315,0.799703,0.028003,9
11,1.462859,0.075673,0.033883,0.001858,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.861198,0.799265,0.805064,0.829045,0.779359,0.814786,0.028099,1
12,0.002687,0.000721,0.000000,0.000000,friedman_mse,auto,10,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
13,0.002269,0.000768,0.000000,0.000000,friedman_mse,auto,100,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
14,0.070204,0.005118,0.010193,0.002564,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.813087,0.767220,0.793052,0.800624,0.763894,0.787575,0.019111,12
15,0.649264,0.062852,0.046896,0.012795,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.863045,0.788126,0.795558,0.812957,0.770864,0.806110,0.031514,8
16,0.090649,0.002867,0.012784,0.002473,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.839501,0.762887,0.763700,0.800854,0.762603,0.785909,0.030535,14
17,0.633647,0.045422,0.038401,0.004539,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.865874,0.788932,0.800157,0.817353,0.779517,0.810367,0.030480,4
18,0.002298,0.000543,0.000000,0.000000,poisson,auto,10,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
19,0.001993,0.000150,0.000000,0.000000,poisson,auto,100,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
20,0.090126,0.006473,0.011610,0.002260,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.827927,0.767005,0.770129,0.804626,0.767360,0.787410,0.024718,13
21,0.585698,0.020862,0.035165,0.003026,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.867351,0.792019,0.804039,0.819018,0.776699,0.811825,0.031054,3
22,0.092183,0.012461,0.010054,0.002215,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.855907,0.785504,0.791087,0.798206,0.757555,0.797652,0.032225,10
23,0.531347,0.010359,0.037788,0.002631,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.861853,0.785235,0.798594,0.823612,0.772578,0.808374,0.031637,6

In [17]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 35
BMI: 35
Children: 1
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 1

In [18]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
#␣,change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[46544.95]